dependencies:
- name: fluentd-elasticsearch
  version: 0.6.4
  repository: "https://kubernetes-charts-incubator.storage.googleapis.com/"
- name: kibana
  version: 0.8.0
  repository: "https://kubernetes-charts.storage.googleapis.com/"
