# Default values for logging-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kibana:
  service:
    type: NodePort
  # env:
    # ELASTICSEARCH_URL: http://elk-fluentd-elasticsearch:9200

fluentd-elasticsearch:
