apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logging-chart.fullname" . }}
  labels:
    app: {{ template "logging-chart.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    addonmanager.kubernetes.io/mode: Reconcile
data:
{{- range $key, $value := .Values.fluentd.configMaps }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
