apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "logging-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.kibana.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  name: {{ template "logging-chart.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.kibana.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.externalPort }}
      targetPort: {{ .Values.kibana.service.internalPort }}
      protocol: TCP
{{- if .Values.kibana.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.kibana.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "logging-chart.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.kibana.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.kibana.service.loadBalancerIP }}
{{- end }}
