apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "logging-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "logging-chart.fullname" . }}
spec:
  replicas: {{ .Values.kibana.replicaCount }}
  template:
    metadata:
    {{- if .Values.kibana.podAnnotations }}
      annotations:
{{ toYaml .Values.kibana.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "logging-chart.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ template "logging-chart.fullname" . }}
      {{- if .Values.kibana.priorityClassName }}
      priorityClassName: "{{ .Values.kibana.priorityClassName }}"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.kibana.image.repository }}:{{ .Values.kibana.image.tag }}"
        imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
        {{- if .Values.kibana.commandline.args }}
        args:
          - "/bin/bash"
          - "/usr/local/bin/kibana-docker"
{{ toYaml .Values.kibana.commandline.args | indent 10 }}
        {{- end }}
        env:
        {{- range $key, $value := .Values.kibana.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        ports:
        - containerPort: {{ .Values.kibana.service.internalPort }}
          name: {{ template "logging-chart.name" . }}
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /ping
        #     port: {{ .Values.kibana.service.internalPort }}
        # readinessProbe:
        #   httpGet:
        #     path: /ping
        #     port: {{ .Values.kibana.service.internalPort }}
        resources:
{{ toYaml .Values.kibana.resources | indent 10 }}
    {{- if .Values.kibana.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.kibana.image.pullSecrets | indent 8 }}
    {{- end }}
    {{- if .Values.kibana.affinity }}
      affinity:
{{ toYaml .Values.kibana.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.kibana.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.kibana.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
{{ toYaml .Values.kibana.tolerations | indent 8 }}
