apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "logging-chart.fullname" . }}
  labels:
    app: {{ template "logging-chart.name" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
